# NUMPY 

Es el paquete científico fundamental para hacer cálculos en el lenguaje de programación python.
La función principal de numpy es la operación de matrices multidimensionales.



In [1]:
# Ejemplo:


# Importación de la librería numpy
import numpy as np

In [2]:
# Creación de una matriz

a = np.arange(15).reshape(3, 5)



In [3]:
#Imprimir la matriz
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
#Imprimir el tamaño de la matriz
a.shape


(3, 5)

In [5]:
#Imprimir el número de dimensiones de la matriz
a.ndim

2

In [6]:
# Imprimir el tipo de datos en la matriz
a.dtype.name


'int32'

In [7]:
# Imprimir el tamaño de un elemento en bytes
a.itemsize

4

In [8]:
#Imprimir el número de elementos en la matriz
a.size

15

In [9]:
#Imprimir el tipo de objeto a
type(a)

numpy.ndarray

In [10]:
#Creación de una matriz con una hilera y tres columnas
b = np.array([6, 7, 8])

In [11]:
#Imprimir la matriz b
b

array([6, 7, 8])

In [12]:
#Imprimir el tipo de objeto b
type(b)

numpy.ndarray